name: CI

on:
  push:
    branches: [ 1.x.x ]
  pull_request:
    branches: [ 1.x.x ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Java 17
        uses: actions/setup-java@v3.0.0
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Execute Gradle build
        run: ./gradlew build
